Models/Supplier.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace FutureFridgesCW.Models
{
    public class Supplier
    {
        [Key]
        public int SupplierId { get; set; }
        public string SupplierName { get; set; }

        public string SupplierEmail { get; set; }

        public int SupplierPhone { get; set; }

        public string SupplierAddress { get; set; }

    }
}

Pages/AddSupplier.cshtml.cs
using FutureFridgesCW.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FutureFridgesCW.Pages
{
    public class AddSupplierModel : PageModel
    {
        private readonly AppDataContext _db;

        [BindProperty]
        public Supplier AddingSupplier { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public AddSupplierModel(AppDataContext db)
        {
            _db = db;
        }

        public void OnGet()
        {

            AddingSupplier = _db.Supplier.Find(Id);

        }

        public IActionResult OnPost()
        {
            _db.Supplier.Update(AddingSupplier);
            _db.SaveChanges();
            return RedirectToPage("/Supplier");
        }

    }
}

Pages/Dashboard.cshtml.cs
using FutureFridgesCW.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.Entity;

namespace FutureFridgesCW.Pages
{
    [Authorize(Roles = "Manager")]
    public class DashboardModel : PageModel
    {

        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public List<IdentityRole> roles { get; set; }

        public List<AppUser> Users { get; set; }
        public DashboardModel(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [BindProperty]
        public string RoleNameToAdd { get; set; }


        [BindProperty]
        public string UpdatePassword { get; set; }
        [BindProperty]
        public string UpdateRole { get; set; }

        public void OnGet()
        {
            
            Users = _userManager.Users.ToList();
            roles =  _roleManager.Roles.ToList();
            
        }
        public async Task<IActionResult> OnPostAsync()
        {

            await _roleManager.CreateAsync(new IdentityRole(RoleNameToAdd.Trim()));
            return RedirectToPage("/Dashboard");

        }
                    
        public async Task<IActionResult> OnGetDeleteAsync(string Id)
        {
            var role = await _roleManager.FindByIdAsync(Id);
            IdentityResult result = await _roleManager.DeleteAsync(role);
            return RedirectToPage("/Dashboard");
        }
        public async Task<IActionResult> OnPostUpdateAsync(string Id)

        {
            var users = await _userManager.FindByIdAsync(Id);
            await _userManager.RemovePasswordAsync(users);
            await _userManager.AddPasswordAsync(users, UpdatePassword);
            return RedirectToPage("/Dashboard");

        }
        public async Task<IActionResult> OnPostRoleAsync(string Id)
        {
            var role = await _userManager.FindByIdAsync(Id);
            await _userManager.AddToRoleAsync(role, UpdateRole);
            return RedirectToPage("/AdminDashboard");
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace FutureFridgesCW.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FutureFridgesCW.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Insert.cshtml.cs
using FutureFridgesCW.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FutureFridgesCW.Pages
{
    //[Authorize(Roles = "Headchef,Chef,Driver")]
    public class InsertModel : PageModel
    {
        private readonly AppDataContext _db;
        public bool queryStringChecker { get; set; }
        public string button { get; set; }

        [BindProperty]
        public Products productGoingIntoFridge { get; set; }
        public bool Save { get; set; }
        public bool Update { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        public InsertModel(AppDataContext db)
        {
            _db = db;
        }


        public void OnGet()
        {

            productGoingIntoFridge = _db.Products.Find(Id);
        }

        public IActionResult OnPost()
        {
            _db.Products.Add(productGoingIntoFridge);
            _db.SaveChanges();
            return RedirectToPage("/Remove");
        }
        public IActionResult OnPostUpdate()
        {

            _db.Products.Update(productGoingIntoFridge);
            _db.SaveChanges();
            return RedirectToPage("/Remove");
        }

    }
    
    
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FutureFridgesCW.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Remove.cshtml.cs
using FutureFridgesCW.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FutureFridgesCW.Pages
{

    public class RemoveModel : PageModel
    {
        public List<Products> Products { get; set; }

        private readonly AppDataContext _db;

        public RemoveModel(AppDataContext db)
        {
            _db = db;
        }

        public void OnGet()
        {
            Products = _db.Products.ToList();
        }

        public IActionResult OnGetDelete(int Id)
        {
            _db.Remove(_db.Products.Find(Id));
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}
    

Pages/Supplier.cshtml.cs
using FutureFridgesCW.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FutureFridgesCW.Pages
{
    public class SupplierModel : PageModel
    {
        public int Id { get; set; }
        public List<Supplier> Suppliers { get; set; }

        private readonly AppDataContext _db;

        public SupplierModel(AppDataContext db)
        {
            _db = db;
        }

       public void OnGet()
        {
            Suppliers=_db.Supplier.ToList();

        }


        public IActionResult OnGetDelete(int Id)
        {
            _db.Remove(_db.Supplier.Find(Id));
            _db.SaveChanges();
            return RedirectToAction("/Supplier");
        }

        public IActionResult OnGetAddSupplier()
        {
            return RedirectToPage("/AddSupplier");
                
                
        }
   


    }
}

Pages/AddSupplier.cshtml
@page
@model FutureFridgesCW.Pages.AddSupplierModel
@{
}

<div class="pageTitle"> <h1>Add Supplier</h1> </div>

      <div class="container">
      <div class="content">
        <form method="post">
          <div class="user-details">
            <div class="input-box">
                    <span class="details"><label asp-for="@Model.AddingSupplier.SupplierId"></label></span>
                    <input placeholder="Supplier ID" asp-for="@Model.AddingSupplier.SupplierId" readonly>
            </div>
            <div class="input-box">
                    <span class="details"><label asp-for="@Model.AddingSupplier.SupplierName"></label></span>
                    <input placeholder=" Enter Supplier's Name" asp-for="@Model.AddingSupplier.SupplierName" required>

            </div>
            <div class="input-box">
                    <span class="details"><label asp-for="@Model.AddingSupplier.SupplierEmail"></label></span>
                    <input placeholder=" Enter Supplier's Email" asp-for="@Model.AddingSupplier.SupplierEmail" required>

            </div>
            <div class="input-box">
                    <span class="details"><label asp-for= "@Model.AddingSupplier.SupplierPhone"></label></span>
                    <input placeholder=" Enter Supplier's Number" asp-for="@Model.AddingSupplier.SupplierPhone" required>
            </div>
            <div class="input-box">
                    <span class="details"><label asp-for= "@Model.AddingSupplier.SupplierAddress"></label></span>
                    <input  placeholder=" Enter Supplier's Address" asp-for="@Model.AddingSupplier.SupplierAddress" required>

            </div>
          </div>

          <div class="button">
            <input type="submit" value="Update">
          </div>

        </form>
      </div>
    </div>

Pages/Dashboard.cshtml
@page
@model FutureFridgesCW.Pages.DashboardModel
@{
}
<div class="text"> Users </div>
<section class="products">
    <div class="products-list">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>User Roles</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

            <tbody>
                    @foreach (var roles in Model.roles)
                    {
                    <tr>
                        <td>@roles.Id</td>
                        <td>@roles.Name</td>
                        <td><a class="button" asp-page-handler="Delete" asp-route-id="@roles.Id">Delete Role</a></td>

                    </tr>
                    }
            </tbody>
            <tr>
                <td>
                    <form class="content" method="post" asp-page-handler="Add">
                        <input asp-for="RoleNameToAdd" />
                        <input class="button" value="Add New Role" type="submit" asp-page="/Dashboard" />
                    </form>
                </td>
            </tr>

        </table>
    </div>

    <div class="products-list">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Admin Dashboard</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var users in Model.Users)
                {
                    <tr>

                        <td> @users.Id </td>
                        <td> @users.Email</td>
                        <td>
                            <form class="content" method="post" asp-page-handler="Update" asp-route-id="@users.Id">
                                <input asp-for="UpdatePassword" />
                                <input type="submit" value="Update Password" class="button" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</section>

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Insert.cshtml
@page
@model FutureFridgesCW.Pages.InsertModel
@{

}

<div class="admin-product-form-container">
    <form method="post" asp-page="/Insert">
        <h3>add a new product</h3>

        <label asp-for="@Model.productGoingIntoFridge.ProductId"></label>
        <input type="text" asp-for="@Model.productGoingIntoFridge.ProductId" readonly />



        <label asp-for="@Model.productGoingIntoFridge.ProductName"></label>
        <input type="text" placeholder="enter product name" asp-for="@Model.productGoingIntoFridge.ProductName" class="box">



        <label asp-for="@Model.productGoingIntoFridge.quantity"></label>
        <input type="number" placeholder="enter product quantity" asp-for="@Model.productGoingIntoFridge.quantity class=" box">

        <label asp-for="@Model.productGoingIntoFridge.expiryDate"></label>
        <input type="text" placeholder="enter product expiry" asp-for="@Model.productGoingIntoFridge.expiryDate" class="box">
        @{
            if (Model.Save)
            {
                <input type="submit" class="btn" value="Store">
            }
            else
            {
                <input type="submit" class="btn" asp-page-handler="Update" value="Store">
            }
        }
    </form>
</div>

Pages/Remove.cshtml
@page
@model FutureFridgesCW.Pages.RemoveModel
@{
}
<div class="add-container">
    <section class="products">
        <div class="products-list">
            <table class="table">
                <thead>
                    <tr>
                        <th>product name</th>
                        <th>Product quantity</th>
                        <th>product expiry</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var action in Model.Products)
                    {

                        <tr>
                            <td>@action.ProductName</td>
                            <td>@action.quantity</td>
                            <td>@action.expiryDate</td>
                            <td>
                                <a class="edit-btn" asp-route-id="@action.ProductId" asp-page="/Insert"> <i class="fas fa-edit"></i> Update </a>
                                <a class="edit-btn" asp-route-id="@action.ProductId" asp-page-handler="Delete">  <i class="fas fa-edit"></i> Delete </a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </section>
</div>

Pages/Supplier.cshtml
@page
@model FutureFridgesCW.Pages.SupplierModel
@{
}


<div class="pageTitle"> <h1>Supplier</h1>   </div>
<div class="add-container">

    <a asp-page="AddSupplier" > <span class=" save-btn">New Supplier</span> </a>

    <section class="products">
        <div class="products-list">
            <table class="table table-sm table-striped table-sortable" style="table-layout: fixed;">
                <thead>
                    <tr>
                        <th data-sort="int">Supplier ID</th>
                        <th data-sort="string">Supplier Name</th>
                        <th> Email</th>
                        <th>Address</th>
                        <th>Phone Number</th>
                        <th>Action</th>

                    </tr>
                </thead>
                @foreach (var action in Model.Suppliers)
                {
                    
                 <tr>
                    <td>@action.SupplierId</td>
                    <td>@action.SupplierName</td>
                    <td>@action.SupplierEmail</td>
                    <td>@action.SupplierPhone</td>
                    <td>@action.SupplierAddress</td>
                    <td>
                            <a class="edit-btn" asp-route-id="@action.SupplierId" asp-page="/AddSupplier"> <i class="fas fa-edit"></i> Update </a>
                            <a class="edit-btn" asp-route-id="@action.SupplierId" asp-page-handler="Delete">  <i class="fas fa-edit"></i> Delete </a>
                    </td>

                    </tr>
                
                
                }

            </table>
        </div>
    </section>

</div>


    <script src="/js/tablesort.min.js"></script>
  <script>document.querySelector('.table-sortable').tsortable()</script>